name = "myghpagesTesting2"
uuid = "72bef197-fe88-440b-bbfb-ee2ce3b5b1ec"
authors = ["Charis P. Michelakis <ch.p.michelakis@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.4.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
